import { toISODate } from "./formatDate";
import { splitSearchTokens } from "./search";
import { getItemColorNames, resolveColorDetails } from "./wardrobeColors";
import { buildDefaultItemTitle } from "./wardrobeTitle";

const placeholderImage = require("../../assets/icon.png");

export const WARDROBE_SORT_OPTIONS = [
  { id: "recent", title: "Недавно добавленные" },
  { id: "outfitCount", title: "По количеству образов" },
];

function ensureArray(value) {
  if (Array.isArray(value)) return value.filter(Boolean);
  if (typeof value === "string" && value.trim()) {
    return value
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean);
  }
  return [];
}

function uniqueStrings(values) {
  return Array.from(new Set(ensureArray(values)));
}

export function normalizeStyleName(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/\s*[_/\\-]+\s*/g, " ")
    .replace(/\s+/g, " ");
}

function uniqueStyleNames(values) {
  const seen = new Set();
  const names = [];

  for (const value of ensureArray(values)) {
    const name = String(value ?? "").trim();
    const normalized = normalizeStyleName(name);
    if (!name || seen.has(normalized)) continue;
    seen.add(normalized);
    names.push(name);
  }

  return names;
}

function resolveCanonicalStyleName(value, styleOptions = [], selectedStyles = []) {
  const normalized = normalizeStyleName(value);
  if (!normalized) return "";
  return (
    [...selectedStyles, ...styleOptions].find((entry) => normalizeStyleName(entry) === normalized)?.trim() ??
    String(value ?? "").trim()
  );
}

export function finalizeDraftStyleInput(draft, styleOptions = []) {
  const rawInput = String(draft?.styleInput ?? "").trim();
  if (!rawInput) {
    return { ...draft, styleInput: "" };
  }

  const nextStyle = resolveCanonicalStyleName(rawInput, styleOptions, draft?.styles ?? draft?.tags ?? []);
  const nextStyles = uniqueStyleNames([...(draft?.styles ?? draft?.tags ?? []), nextStyle]);
  return {
    ...draft,
    styles: nextStyles,
    tags: nextStyles,
    styleInput: "",
  };
}

function isBlank(value) {
  return String(value ?? "").trim().length === 0;
}

const REQUIRED_DRAFT_FIELD_CONFIG = {
  title: {
    label: "название",
    message: "Заполните название вещи",
  },
  catalogId: {
    label: "каталог",
    message: "Выберите каталог",
  },
  categoryId: {
    label: "категория",
    message: "Выберите категорию",
  },
  subcategory: {
    label: "подкатегория",
    message: "Выберите или введите подкатегорию",
  },
  primaryImageFileId: {
    label: "изображение вещи",
    message: "Выберите изображение вещи",
  },
  status: {
    label: "статус",
    message: "Выберите статус",
  },
};

export function getWardrobeDraftValidationIssues(draft, options = {}) {
  const issues = [];
  const requirePrimaryImage = Boolean(options.requirePrimaryImage);

  if (isBlank(draft?.title)) {
    issues.push({ field: "title", ...REQUIRED_DRAFT_FIELD_CONFIG.title });
  }
  if (isBlank(draft?.catalogId)) {
    issues.push({ field: "catalogId", ...REQUIRED_DRAFT_FIELD_CONFIG.catalogId });
  }
  if (isBlank(draft?.categoryId)) {
    issues.push({ field: "categoryId", ...REQUIRED_DRAFT_FIELD_CONFIG.categoryId });
  }
  if (isBlank(draft?.subcategory)) {
    issues.push({ field: "subcategory", ...REQUIRED_DRAFT_FIELD_CONFIG.subcategory });
  }
  if (requirePrimaryImage && isBlank(draft?.primaryImageFileId)) {
    issues.push({ field: "primaryImageFileId", ...REQUIRED_DRAFT_FIELD_CONFIG.primaryImageFileId });
  }
  if (isBlank(draft?.status)) {
    issues.push({ field: "status", ...REQUIRED_DRAFT_FIELD_CONFIG.status });
  }

  return issues;
}

export function getWardrobeDraftValidationMessage(draft, options = {}) {
  const issues = getWardrobeDraftValidationIssues(draft, options);
  if (!issues.length) return "";
  if (issues.length === 1) {
    return issues[0].message;
  }
  return `Заполните обязательные поля: ${issues.map((issue) => issue.label).join(", ")}`;
}

function applyAutoGeneratedTitle(draft, colorOptions = [], options = {}) {
  const currentTitle = String(draft.title ?? "").trim();
  const previousAutoTitle = String(draft._autoTitle ?? "").trim();
  const nextAutoTitle = buildDefaultItemTitle(draft.colorDetails ?? draft.colorIds ?? [], draft.subcategory, colorOptions);
  if (options.suppressAutoTitle) {
    return {
      ...draft,
      title: currentTitle,
      _autoTitle: nextAutoTitle,
    };
  }
  const shouldReplaceTitle = !currentTitle || currentTitle === previousAutoTitle;

  return {
    ...draft,
    title: shouldReplaceTitle ? nextAutoTitle : currentTitle,
    _autoTitle: nextAutoTitle,
  };
}

export function normalizeWardrobeItemDraft(draft, previousItem, colorOptions = [], options = {}) {
  const base = previousItem ?? {};
  const seasonOptions = uniqueStrings(options.seasonOptions);
  const colorIds = uniqueStrings(draft.colorIds ?? base.colorIds);
  const colorDetails = resolveColorDetails(colorIds, colorOptions, draft.colorDetails ?? base.colorDetails);
  const initialSeasons = uniqueStrings(draft.seasons ?? draft.season ?? base.seasons ?? base.season);
  const seasons = initialSeasons.length ? initialSeasons : base.id ? initialSeasons : seasonOptions;
  const styles = uniqueStyleNames(draft.styles ?? draft.tags ?? base.styles ?? base.tags);
  const status = draft.status ?? base.status ?? options.statusOptions?.[0]?.id ?? "active";

  return applyAutoGeneratedTitle(
    {
      ...base,
      ...draft,
      image: draft.image ?? base.image ?? placeholderImage,
      title: (draft.title ?? base.title ?? "").trim(),
      catalogId: draft.catalogId ?? base.catalogId ?? "main",
      categoryId: draft.categoryId ?? base.categoryId ?? "tops",
      subcategory: draft.subcategory ?? base.subcategory ?? "",
      colorIds,
      colorDetails,
      brand: draft.brand ?? base.brand ?? "",
      seasons,
      season: seasons,
      styles,
      tags: styles,
      styleInput: draft.styleInput ?? base.styleInput ?? "",
      status,
      createdAt: draft.createdAt ?? base.createdAt ?? toISODate(new Date()),
      outfitCount: Number(draft.outfitCount ?? base.outfitCount ?? 0),
      isArchived: draft.isArchived ?? base.isArchived ?? status === "archived",
      notes: draft.notes ?? base.notes ?? "",
      sourceType: draft.sourceType ?? base.sourceType,
      primaryImageFileId: draft.primaryImageFileId ?? base.primaryImageFileId ?? null,
      categoryPrediction: draft.categoryPrediction ?? base.categoryPrediction ?? null,
      subcategorySuggestions:
        draft.subcategorySuggestions ??
        draft.categoryPrediction?.top3 ??
        base.subcategorySuggestions ??
        [],
      colorPrediction: draft.colorPrediction ?? base.colorPrediction ?? null,
      _autoTitle: draft._autoTitle ?? base._autoTitle ?? "",
    },
    colorOptions,
    options
  );
}

function normalizeText(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/ё/g, "е")
    .replace(/[^a-zа-я0-9\s-]/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function stemWord(word) {
  let value = normalizeText(word);
  const patterns = [
    /ыми$/u,
    /ими$/u,
    /ого$/u,
    /ему$/u,
    /ому$/u,
    /ами$/u,
    /ями$/u,
    /ая$/u,
    /яя$/u,
    /ое$/u,
    /ее$/u,
    /ые$/u,
    /ие$/u,
    /ый$/u,
    /ий$/u,
    /ой$/u,
    /ую$/u,
    /юю$/u,
    /ов$/u,
    /ев$/u,
    /ом$/u,
    /ем$/u,
    /ам$/u,
    /ям$/u,
    /ах$/u,
    /ях$/u,
    /ы$/u,
    /и$/u,
    /а$/u,
    /я$/u,
    /о$/u,
    /е$/u,
  ];

  for (const pattern of patterns) {
    if (value.length > 4 && pattern.test(value)) {
      value = value.replace(pattern, "");
      break;
    }
  }

  return value;
}

function splitToSearchTokens(values) {
  return values
    .flatMap((value) => normalizeText(value).split(" "))
    .map((entry) => stemWord(entry))
    .filter(Boolean);
}

export function getOutfitCountMap(outfits) {
  return outfits.reduce((acc, outfit) => {
    for (const itemId of outfit.itemIds ?? []) {
      acc[itemId] = (acc[itemId] ?? 0) + 1;
    }
    return acc;
  }, {});
}

export function formatWardrobeItemCount(count) {
  const value = Math.abs(Number(count) || 0);
  const lastTwo = value % 100;
  const last = value % 10;

  if (lastTwo >= 11 && lastTwo <= 14) {
    return `${count} вещей`;
  }

  if (last === 1) {
    return `${count} вещь`;
  }

  if (last >= 2 && last <= 4) {
    return `${count} вещи`;
  }

  return `${count} вещей`;
}

export function matchesWardrobeSearch(item, query, categories, catalogs) {
  if (!query?.trim()) return true;

  const category = categories.find((entry) => entry.id === item.categoryId);
  const catalog = catalogs.find((entry) => entry.id === item.catalogId);
  const fieldTokens = splitSearchTokens([
    item.title,
    category?.title,
    catalog?.title,
    item.subcategory,
    item.brand,
    item.status,
    ...getItemColorNames(item),
    ...(item.seasons ?? item.season ?? []),
    ...(item.styles ?? item.tags ?? []),
  ]);
  const queryTokens = splitSearchTokens([query]);

  return queryTokens.every((token) =>
    fieldTokens.some((fieldToken) => fieldToken.includes(token) || token.includes(fieldToken))
  );
}

function includesValue(filterValue, actualValue) {
  if (!filterValue || (Array.isArray(filterValue) && filterValue.length === 0)) return true;

  const actualValues = Array.isArray(actualValue) ? actualValue : [actualValue];
  const filterValues = Array.isArray(filterValue) ? filterValue : [filterValue];

  return filterValues.some((value) => actualValues.includes(value));
}

function matchesColorFilter(item, colorFilter) {
  if (!colorFilter?.length) return true;
  const actualColorIds = item.colorIds ?? [];
  const actualParentIds = (item.colorDetails ?? []).map((entry) => entry.parentColorId).filter(Boolean);
  return colorFilter.some((value) => actualColorIds.includes(value) || actualParentIds.includes(value));
}

export function applyWardrobeFilters(items, filters, outfitCountMap = {}) {
  return items.filter((item) => {
    if (!includesValue(filters.catalogId, item.catalogId)) return false;
    if (!includesValue(filters.categoryId, item.categoryId)) return false;
    if (!includesValue(filters.subcategory, item.subcategory)) return false;
    if (!matchesColorFilter(item, filters.color)) return false;
    if (!includesValue(filters.season, item.seasons ?? item.season ?? [])) return false;
    if (!includesValue(filters.style, item.styles ?? item.tags ?? [])) return false;
    if (!includesValue(filters.brand, item.brand)) return false;
    if (!includesValue(filters.status, item.status)) return false;

    if (filters.outfitParticipation === "withOutfits" && (outfitCountMap[item.id] ?? item.outfitCount ?? 0) === 0) {
      return false;
    }

    if (filters.outfitParticipation === "withoutOutfits" && (outfitCountMap[item.id] ?? item.outfitCount ?? 0) > 0) {
      return false;
    }

    return true;
  });
}

export function sortWardrobeItems(items, sortBy, outfitCountMap = {}) {
  const copy = items.slice();

  if (sortBy === "outfitCount") {
    return copy.sort(
      (left, right) =>
        (outfitCountMap[right.id] ?? right.outfitCount ?? 0) - (outfitCountMap[left.id] ?? left.outfitCount ?? 0)
    );
  }

  return copy.sort((left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime());
}

function unique(values) {
  return Array.from(new Set(values.filter(Boolean))).sort((left, right) => left.localeCompare(right, "ru"));
}

export function getWardrobeFilterOptions(items, colorOptions = [], options = {}) {
  return {
    subcategories: unique(items.map((item) => item.subcategory)),
    colors: colorOptions,
    seasons: options.seasonOptions?.length ? options.seasonOptions : unique(items.flatMap((item) => item.seasons ?? item.season ?? [])),
    styles: options.styleOptions?.length ? options.styleOptions : unique(items.flatMap((item) => item.styles ?? item.tags ?? [])),
    brands: unique(items.map((item) => item.brand)),
    statuses: options.statusOptions?.length ? options.statusOptions : unique(items.map((item) => item.status)),
  };
}

export function createDraftFromItem(item, colorOptions = [], options = {}) {
  return normalizeWardrobeItemDraft(item, undefined, colorOptions, options);
}

export function getStatusMeta(statusId, statusOptions = []) {
  return statusOptions.find((status) => status.id === statusId) ?? statusOptions[0] ?? { id: statusId, title: statusId || "" };
}

export function createEmptyWardrobeFilters(overrides = {}) {
  return {
    catalogId: [],
    categoryId: [],
    subcategory: [],
    color: [],
    season: [],
    style: [],
    brand: [],
    status: [],
    outfitParticipation: "",
    ...overrides,
  };
}
