export const Routes = {
  Home: "Home",
  NewsHome: "NewsHome",
  PostDetails: "PostDetails",
  WardrobeHome: "WardrobeHome",
  WardrobeAllItems: "WardrobeAllItems",
  WardrobeCategory: "WardrobeCategory",
  WardrobeItemDetails: "WardrobeItemDetails",
  WardrobeAddItemMenu: "WardrobeAddItemMenu",
  WardrobeAddFromPhoto: "WardrobeAddFromPhoto",
  WardrobeAddFromGallery: "WardrobeAddFromGallery",
  WardrobeAddFromCatalog: "WardrobeAddFromCatalog",
  WardrobeProcessingStub: "WardrobeProcessingStub",
  WardrobeConfirmItem: "WardrobeConfirmItem",
  WardrobeManageCatalogs: "WardrobeManageCatalogs",
  WardrobeManageCategories: "WardrobeManageCategories",
  WardrobeArchive: "WardrobeArchive",
  OutfitsHome: "OutfitsHome",
  OutfitDetails: "OutfitDetails",
  OutfitEditor: "OutfitEditor",
  AccountHome: "AccountHome",
  Settings: "Settings",
  Category: "WardrobeCategory",
  ItemDetails: "WardrobeItemDetails",
  AddItem: "WardrobeAddItemMenu",
};
